### PR TITLE
Add feature to insert video clip of A-B loop and other features

### PR DESCRIPTION
**Pull request by stardiviner**

### CODE REVIEW

**Comment by stardiviner** [comment]
Here is the link of [ffmpeg-utils](https://repo.or.cz/ffmpeg-utils.git)

**Comment by stardiviner** [comment]
UPDATE: `ffmpeg-utils` now is available on MELPA, it is ready for dependency now.

**Comment by stardiviner** [comment]
Long time no response, so close it now.

**Comment by stardiviner** [comment]
> @stardiviner Sorry I didn't notice before, I feel like have replied in the issue?
> 
> Here's my consideration:
> 
> * I hope it's a separate file like org-ref, because not everyone might need this feature, so don't put it in the main file to require ffmpeg.

I'm not only using org-media-note for taking notes, also for watching movies, use org-media-note to take video clips to store liked clips, then delete the original movie video for saving disk size.

> * How universal is inserting a video clip? Or is inserting a gif more universal? It seems that there are a lot of parameters configured inside. [Taking notes from videos using Emacs](https://gist.github.com/iocanel/adc1310fce6a261567f9582cf6057fbc)

My patch is not very suitable might. If possible, I hope you can implement this feature. WDYT?

**Comment by yuchen-lea** [comment]
What do you think the necessity of introducing the ffmpeg-utils package rather than using ffmpeg command directly? I feel this package is too trivial, if there are other needs in the future such as converting to gif, converting audio, etc., I still have to write extra functions, or submit PRs to ffmpeg-utils.

**Comment by yuchen-lea** [comment]
Got it. Then I'm going to reimplement this feature. 

Since I prefer to prioritize the native shortcuts of mpv, the plan is to change mpv-seek-forward/backward-small to the previous frame and the next frame, using the shortcuts . and , respectively.

**Comment by stardiviner** [comment]
> Got it. Then I'm going to reimplement this feature.

That's great!

> Since I prefer to prioritize the native shortcuts of mpv, how about change mpv-seek-forward/backward-small to the previous frame and the next frame, using the shortcuts . and , respectively?

You're more familiar with mpv. I agree with your idea.

**Comment by yuchen-lea** [comment]
The latest update supports capturing clips from ab loops, See more: Functions, Note-`S` and Config-`t l`.
If you need more customized clip function, add to `org-media-note-capture-ab-loop-functions-alist`

**Comment by stardiviner** [comment]
Thanks for your work. I checked out new feature.

**Comment by yuchen-lea** [comment]
Considering there are various needs for playback control, and there is no frequent need to switch between forward and backward steps in a short time, no shortcut keys have been added in Hydra for minor range adjustments like 0.1s. 

Instead, a new feature has been added to customize the forward and backward steps, which currently supports three methods: seconds, percentage, or frames. 

I think this reached a good balance between flexibility and simplicity.

cab95d2

**Comment by stardiviner** [comment]
Hmm, I agree with your considering. Too complex hydra UI is not good.

**Pull request closed without merging**
